/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trab01_.Interfaces;

import trab01_.Codigos.Graph;

/**
 *
 * @author user
 */
public class IGrafo extends javax.swing.JFrame {

    /**
     * Creates new form IGrafo
     * @param lista
     */
    
    private Graph g;
    
    public IGrafo(Graph g) {
        this.g = g;
        initComponents();
    }
    public IGrafo(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camBtn = new javax.swing.JButton();
        primBtn = new javax.swing.JButton();
        krusBtn = new javax.swing.JButton();
        largBtn = new javax.swing.JButton();
        profBtn = new javax.swing.JButton();
        grafiLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        dijkstraBtn = new javax.swing.JButton();
        bellmanBtn = new javax.swing.JButton();
        visBtn = new javax.swing.JButton();
        conexBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funções de Grafos");

        camBtn.setText("CAMINHO entre Vértices");
        camBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camBtnActionPerformed(evt);
            }
        });

        primBtn.setText("Algoritmo de PRIM");
        primBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primBtnActionPerformed(evt);
            }
        });

        krusBtn.setText("Algoritmo de KRUSKAL");
        krusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krusBtnActionPerformed(evt);
            }
        });

        largBtn.setText("Busca em LARGURA");
        largBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largBtnActionPerformed(evt);
            }
        });

        profBtn.setText("Busca em PROFUNDIDADE");
        profBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profBtnActionPerformed(evt);
            }
        });

        grafiLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grafiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grafiLabel.setText("Grafo");

        backBtn.setText("Voltar");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        dijkstraBtn.setText("Algoritmo de DIJKSTRA");
        dijkstraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dijkstraBtnActionPerformed(evt);
            }
        });

        bellmanBtn.setText("Algoritmo de BELLMAN-FORD");
        bellmanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bellmanBtnActionPerformed(evt);
            }
        });

        visBtn.setText("Visualizar");
        visBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visBtnActionPerformed(evt);
            }
        });

        conexBtn.setText("Verificar a CONEXIDADE");
        conexBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grafiLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(krusBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(primBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(camBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(largBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(visBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dijkstraBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bellmanBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(conexBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(grafiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(largBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dijkstraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bellmanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conexBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(krusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(camBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void primBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primBtnActionPerformed
        IPrim p = new IPrim(g);
        p.setVisible(true);
    }//GEN-LAST:event_primBtnActionPerformed

    private void profBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profBtnActionPerformed
        IProfundidade d = new IProfundidade(g);
        d.setVisible(true);
    }//GEN-LAST:event_profBtnActionPerformed

    private void largBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largBtnActionPerformed
        ILargura w = new ILargura(g);
        w.setVisible(true);
    }//GEN-LAST:event_largBtnActionPerformed

    private void krusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krusBtnActionPerformed
        IKruskal k = new IKruskal(g);
        k.setVisible(true);
    }//GEN-LAST:event_krusBtnActionPerformed

    private void visBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visBtnActionPerformed
        IImpressao imp = new IImpressao(g);
        imp.setVisible(true);
        
    }//GEN-LAST:event_visBtnActionPerformed

    private void bellmanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bellmanBtnActionPerformed
        IBellman b = new IBellman(g, 'g');
        b.setVisible(true);
    }//GEN-LAST:event_bellmanBtnActionPerformed

    private void dijkstraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dijkstraBtnActionPerformed
        IDijkstra d = new IDijkstra(g, 'g');
        d.setVisible(true);
    }//GEN-LAST:event_dijkstraBtnActionPerformed

    private void camBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camBtnActionPerformed

    private void conexBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexBtnActionPerformed
        IConexo con = new IConexo(g);
        con.setVisible(true);
    }//GEN-LAST:event_conexBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IGrafo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bellmanBtn;
    private javax.swing.JButton camBtn;
    private javax.swing.JButton conexBtn;
    private javax.swing.JButton dijkstraBtn;
    private javax.swing.JLabel grafiLabel;
    private javax.swing.JButton krusBtn;
    private javax.swing.JButton largBtn;
    private javax.swing.JButton primBtn;
    private javax.swing.JButton profBtn;
    private javax.swing.JButton visBtn;
    // End of variables declaration//GEN-END:variables
}
